export type DealerType = "kili" | "delfy";

export interface Dealer {
  id: string;
  name: string;
  type: DealerType;
  address: string;
  city: string;
  lat: number;
  lng: number;
  phone?: string;
  email?: string;
  url?: string;
}

export const dealers: Dealer[] = [
  // ── KILI ─────────────────────────────────────────────────────────────
  {
    id: "kili-slapanice",
    name: "Kili – Centrála Šlapanice",
    type: "kili",
    address: "Hybešova 1647",
    city: "Šlapanice",
    lat: 49.1772,
    lng: 16.7025,
    phone: "+420 544 228 155",
    email: "obchod@kili.cz",
    url: "https://www.kili.cz/obchodni-centra/centrala-slapanice/",
  },
  {
    id: "kili-bystrice",
    name: "Kili – OC Bystřice nad Pernštejnem",
    type: "kili",
    address: "Průmyslová 660",
    city: "Bystřice nad Pernštejnem",
    lat: 49.521,
    lng: 16.266,
    phone: "+420 724 337 665",
    email: "bystricenp@kili.cz",
    url: "https://www.kili.cz/obchodni-centra/oc-bystrice-nad-pernstejnem/",
  },
  {
    id: "kili-cb",
    name: "Kili – OC České Budějovice",
    type: "kili",
    address: "U Pily 723 – Nová Vrata",
    city: "České Budějovice",
    lat: 48.9745,
    lng: 14.475,
    phone: "+420 602 153 954",
    email: "cbudejovice@kili.cz",
    url: "https://www.kili.cz/obchodni-centra/oc-ceske-budejovice/",
  },
  {
    id: "kili-humpolec",
    name: "Kili – OC Humpolec",
    type: "kili",
    address: "Okružní 1778",
    city: "Humpolec",
    lat: 49.54,
    lng: 15.359,
    phone: "+420 605 228 027",
    email: "humpolec@kili.cz",
    url: "https://www.kili.cz/obchodni-centra/oc-humpolec/",
  },
  {
    id: "kili-prostejov",
    name: "Kili – OC Prostějov",
    type: "kili",
    address: "Kpt. Nálepy 2",
    city: "Prostějov",
    lat: 49.472,
    lng: 17.111,
    phone: "+420 602 430 078",
    email: "prostejov@kili.cz",
    url: "https://www.kili.cz/obchodni-centra/oc-prostejov/",
  },
  {
    id: "kili-starecprostejov",
    name: "Kili – OC Strakonice",
    type: "kili",
    address: "Písecká 284",
    city: "Strakonice",
    lat: 49.261,
    lng: 13.902,
    phone: "+420 723 067 076",
    email: "strakonice@kili.cz",
    url: "https://www.kili.cz/obchodni-centra/oc-strakonice/",
  },
  {
    id: "kili-tabor",
    name: "Kili – OC Tábor",
    type: "kili",
    address: "Vošická 2604",
    city: "Tábor",
    lat: 49.415,
    lng: 14.66,
    phone: "+420 724 771 603",
    email: "tabor@kili.cz",
    url: "https://www.kili.cz/obchodni-centra/oc-tabor/",
  },
  {
    id: "kili-trebic",
    name: "Kili – OC Třebíč (Stařeč)",
    type: "kili",
    address: "Stařeč 513",
    city: "Stařeč",
    lat: 49.221,
    lng: 15.88,
    phone: "+420 724 932 748",
    email: "trebic@kili.cz",
    url: "https://www.kili.cz/obchodni-centra/oc-trebic-starec/",
  },
  {
    id: "kili-zlin",
    name: "Kili – OC Zlín",
    type: "kili",
    address: "Cecilka 228",
    city: "Zlín – Příluky",
    lat: 49.231,
    lng: 17.664,
    phone: "+420 602 408 793",
    email: "zlin@kili.cz",
    url: "https://www.kili.cz/obchodni-centra/oc-zlin/",
  },
  {
    id: "kili-zdar",
    name: "Kili – OC Žďár nad Sázavou",
    type: "kili",
    address: "Brněnská 30",
    city: "Žďár nad Sázavou",
    lat: 49.564,
    lng: 15.939,
    phone: "+420 602 433 117",
    email: "zdarns@kili.cz",
    url: "https://www.kili.cz/obchodni-centra/oc-zdar-nad-sazavou/",
  },

  // ── DELFY STAVIVA ────────────────────────────────────────────────────
  {
    id: "delfy-most",
    name: "Delfy Staviva – Most",
    type: "delfy",
    address: "Dělnická 209",
    city: "Most – Velebudice",
    lat: 50.503,
    lng: 13.636,
    phone: "+420 731 356 353",
    email: "most@delfystaviva.cz",
    url: "https://delfystaviva.cz",
  },
  {
    id: "delfy-litvinov",
    name: "Delfy Staviva – Litvínov",
    type: "delfy",
    address: "S.K. Neumanna 1521",
    city: "Litvínov",
    lat: 50.6,
    lng: 13.611,
    phone: "+420 731 356 536",
    email: "litvinov@delfystaviva.cz",
    url: "https://delfystaviva.cz",
  },
  {
    id: "delfy-jiretin",
    name: "Delfy Staviva – Horní Jiřetín",
    type: "delfy",
    address: "Dolní Jiřetín – Záluží",
    city: "Horní Jiřetín",
    lat: 50.534,
    lng: 13.523,
    phone: "+420 734 594 549",
    email: "jiretin@delfystaviva.cz",
    url: "https://delfystaviva.cz",
  },
  {
    id: "delfy-podborany",
    name: "Delfy Staviva – Podbořany",
    type: "delfy",
    address: "Kadaňská 646",
    city: "Podbořany",
    lat: 50.227,
    lng: 13.409,
    phone: "+420 732 932 322",
    email: "podborany@delfystaviva.cz",
    url: "https://delfystaviva.cz",
  },
];

export const dealerConfig: Record<DealerType, { label: string; color: string; bgColor: string }> = {
  kili:  { label: "Kili",          color: "#1a6b3a", bgColor: "#d1fae5" },
  delfy: { label: "Delfy Staviva", color: "#b45309", bgColor: "#fef3c7" },
};
