export type DealerType = "kili" | "drevotrust" | "delfy";

export interface Dealer {
  id: string;
  name: string;
  type: DealerType;
  address: string;
  city: string;
  lat: number;
  lng: number;
  phone?: string;
  email?: string;
  url?: string;
}

export const dealers: Dealer[] = [
  // ── KILI ─────────────────────────────────────────────────────────────
  {
    id: "kili-slapanice",
    name: "Kili – Centrála Šlapanice",
    type: "kili",
    address: "Hybešova 1647",
    city: "Šlapanice",
    lat: 49.1772,
    lng: 16.7025,
    phone: "+420 544 228 155",
    email: "obchod@kili.cz",
    url: "https://www.kili.cz/obchodni-centra/centrala-slapanice/",
  },
  {
    id: "kili-bystrice",
    name: "Kili – OC Bystřice nad Pernštejnem",
    type: "kili",
    address: "Průmyslová 660",
    city: "Bystřice nad Pernštejnem",
    lat: 49.521,
    lng: 16.266,
    phone: "+420 724 337 665",
    email: "bystricenp@kili.cz",
    url: "https://www.kili.cz/obchodni-centra/oc-bystrice-nad-pernstejnem/",
  },
  {
    id: "kili-cb",
    name: "Kili – OC České Budějovice",
    type: "kili",
    address: "U Pily 723 – Nová Vrata",
    city: "České Budějovice",
    lat: 48.9745,
    lng: 14.475,
    phone: "+420 602 153 954",
    email: "cbudejovice@kili.cz",
    url: "https://www.kili.cz/obchodni-centra/oc-ceske-budejovice/",
  },
  {
    id: "kili-humpolec",
    name: "Kili – OC Humpolec",
    type: "kili",
    address: "Okružní 1778",
    city: "Humpolec",
    lat: 49.54,
    lng: 15.359,
    phone: "+420 605 228 027",
    email: "humpolec@kili.cz",
    url: "https://www.kili.cz/obchodni-centra/oc-humpolec/",
  },
  {
    id: "kili-prostejov",
    name: "Kili – OC Prostějov",
    type: "kili",
    address: "Kpt. Nálepy 2",
    city: "Prostějov",
    lat: 49.472,
    lng: 17.111,
    phone: "+420 602 430 078",
    email: "prostejov@kili.cz",
    url: "https://www.kili.cz/obchodni-centra/oc-prostejov/",
  },
  {
    id: "kili-strakonice",
    name: "Kili – OC Strakonice",
    type: "kili",
    address: "Písecká 284",
    city: "Strakonice",
    lat: 49.261,
    lng: 13.902,
    phone: "+420 723 067 076",
    email: "strakonice@kili.cz",
    url: "https://www.kili.cz/obchodni-centra/oc-strakonice/",
  },
  {
    id: "kili-tabor",
    name: "Kili – OC Tábor",
    type: "kili",
    address: "Vošická 2604",
    city: "Tábor",
    lat: 49.415,
    lng: 14.66,
    phone: "+420 724 771 603",
    email: "tabor@kili.cz",
    url: "https://www.kili.cz/obchodni-centra/oc-tabor/",
  },
  {
    id: "kili-trebic",
    name: "Kili – OC Třebíč (Starec)",
    type: "kili",
    address: "Starec 513",
    city: "Starec",
    lat: 49.221,
    lng: 15.88,
    phone: "+420 724 932 748",
    email: "trebic@kili.cz",
    url: "https://www.kili.cz/obchodni-centra/oc-trebic-starec/",
  },
  {
    id: "kili-zlin",
    name: "Kili – OC Zlín",
    type: "kili",
    address: "Cecilka 228",
    city: "Zlín – Příluky",
    lat: 49.231,
    lng: 17.664,
    phone: "+420 602 408 793",
    email: "zlin@kili.cz",
    url: "https://www.kili.cz/obchodni-centra/oc-zlin/",
  },
  {
    id: "kili-zdar",
    name: "Kili – OC Žďár nad Sázavou",
    type: "kili",
    address: "Brněnská 30",
    city: "Žďár nad Sázavou",
    lat: 49.564,
    lng: 15.939,
    phone: "+420 602 433 117",
    email: "zdarns@kili.cz",
    url: "https://www.kili.cz/obchodni-centra/oc-zdar-nad-sazavou/",
  },

  // ── DŘEVOTRUST ───────────────────────────────────────────────────────
  { id: "dt-bohumin",    name: "Dřevotrust – Bohumín",              type: "drevotrust", address: "1. máje 122",               city: "Bohumín",               lat: 49.909, lng: 18.356, url: "https://www.drevotrust.cz" },
  { id: "dt-ctestejsin", name: "Dřevotrust – Český Těšín",          type: "drevotrust", address: "Jablunkovská 30",            city: "Český Těšín",           lat: 49.747, lng: 18.624, url: "https://www.drevotrust.cz" },
  { id: "dt-fm",         name: "Dřevotrust – Frýdek-Místek",        type: "drevotrust", address: "Jamnická 348",               city: "Frýdek-Místek",         lat: 49.681, lng: 18.373, url: "https://www.drevotrust.cz" },
  { id: "dt-karvina",    name: "Dřevotrust – Karviná",              type: "drevotrust", address: "Rudé armády",                city: "Karviná",               lat: 49.854, lng: 18.543, url: "https://www.drevotrust.cz" },
  { id: "dt-novyjicin",  name: "Dřevotrust – Nový Jičín",           type: "drevotrust", address: "Nádražní 2318/45",           city: "Nový Jičín",            lat: 49.594, lng: 18.013, url: "https://www.drevotrust.cz" },
  { id: "dt-ostrava",    name: "Dřevotrust – Ostrava",              type: "drevotrust", address: "U Haldy 189/59",             city: "Ostrava",               lat: 49.834, lng: 18.282, url: "https://www.drevotrust.cz" },
  { id: "dt-hodonin",    name: "Dřevotrust – Hodonín",              type: "drevotrust", address: "Bratislavská 4495/14",       city: "Hodonín",               lat: 48.848, lng: 17.133, url: "https://www.drevotrust.cz" },
  { id: "dt-hk",         name: "Dřevotrust – Hradec Králové",       type: "drevotrust", address: "Dřevařská 551",              city: "Hradec Králové",        lat: 50.21,  lng: 15.832, url: "https://www.drevotrust.cz" },
  { id: "dt-trutnov",    name: "Dřevotrust – Trutnov",              type: "drevotrust", address: "Zahradní ulice",             city: "Trutnov",               lat: 50.561, lng: 15.913, url: "https://www.drevotrust.cz" },
  { id: "dt-humpolec",   name: "Dřevotrust – Humpolec",             type: "drevotrust", address: "Nerudova 603",               city: "Humpolec",              lat: 49.542, lng: 15.361, url: "https://www.drevotrust.cz" },
  { id: "dt-jesenik",    name: "Dřevotrust – Jeseník",              type: "drevotrust", address: "Lipovská 735/84",            city: "Jeseník",               lat: 50.227, lng: 17.202, url: "https://www.drevotrust.cz" },
  { id: "dt-lipnik",     name: "Dřevotrust – Lipník nad Bečvou",   type: "drevotrust", address: "Tyršova 1559",               city: "Lipník nad Bečvou",     lat: 49.524, lng: 17.588, url: "https://www.drevotrust.cz" },
  { id: "dt-olomouc",    name: "Dřevotrust – Olomouc",              type: "drevotrust", address: "Jeremenkova 10",             city: "Olomouc",               lat: 49.594, lng: 17.251, url: "https://www.drevotrust.cz" },
  { id: "dt-prostejov",  name: "Dřevotrust – Prostějov",            type: "drevotrust", address: "Určická 5101",               city: "Prostějov",             lat: 49.474, lng: 17.112, url: "https://www.drevotrust.cz" },
  { id: "dt-sumperk",    name: "Dřevotrust – Šumperk",              type: "drevotrust", address: "Příčná 10",                  city: "Šumperk",               lat: 49.966, lng: 16.971, url: "https://www.drevotrust.cz" },
  { id: "dt-klatovy",    name: "Dřevotrust – Klatovy",              type: "drevotrust", address: "Dr. Sedláka 466/3",          city: "Klatovy",               lat: 49.395, lng: 13.295, url: "https://www.drevotrust.cz" },
  { id: "dt-plzen",      name: "Dřevotrust – Plzeň",                type: "drevotrust", address: "Jateční 36",                 city: "Plzeň",                 lat: 49.738, lng: 13.374, url: "https://www.drevotrust.cz" },
  { id: "dt-kolin",      name: "Dřevotrust – Kolín",                type: "drevotrust", address: "K Vinici 1472",              city: "Kolín",                 lat: 50.027, lng: 15.201, url: "https://www.drevotrust.cz" },
  { id: "dt-kromeriz",   name: "Dřevotrust – Kroměříž",             type: "drevotrust", address: "Skopalíkova 2600",           city: "Kroměříž",              lat: 49.296, lng: 17.392, url: "https://www.drevotrust.cz" },
  { id: "dt-valmez",     name: "Dřevotrust – Valašské Meziříčí",   type: "drevotrust", address: "Zašovská 750",               city: "Valašské Meziříčí",     lat: 49.472, lng: 17.972, url: "https://www.drevotrust.cz" },
  { id: "dt-vsetin",     name: "Dřevotrust – Vsetín",               type: "drevotrust", address: "Na Lapači 856",              city: "Vsetín",                lat: 49.339, lng: 17.997, url: "https://www.drevotrust.cz" },
  { id: "dt-liberec",    name: "Dřevotrust – Liberec",              type: "drevotrust", address: "Kateřinská 725, Stráž nad Nisou", city: "Liberec",          lat: 50.763, lng: 15.054, url: "https://www.drevotrust.cz" },
  { id: "dt-turnov",     name: "Dřevotrust – Turnov",               type: "drevotrust", address: "Vesecko 482",                city: "Turnov",                lat: 50.586, lng: 15.158, url: "https://www.drevotrust.cz" },
  { id: "dt-mllazne",    name: "Dřevotrust – Mariánské Lázně",      type: "drevotrust", address: "Tepelská 551",               city: "Mariánské Lázně",       lat: 49.965, lng: 12.702, url: "https://www.drevotrust.cz" },
  { id: "dt-vysokemyto", name: "Dřevotrust – Vysoké Mýto",          type: "drevotrust", address: "Průmyslová 75",              city: "Vysoké Mýto",           lat: 49.96,  lng: 16.162, url: "https://www.drevotrust.cz" },

  // ── DELFY STAVIVA ────────────────────────────────────────────────────
  {
    id: "delfy-most",
    name: "Delfy Staviva – Most",
    type: "delfy",
    address: "Dělnická 209",
    city: "Most – Velebudice",
    lat: 50.503,
    lng: 13.636,
    phone: "+420 731 356 353",
    email: "most@delfystaviva.cz",
    url: "https://delfystaviva.cz",
  },
  {
    id: "delfy-litvinov",
    name: "Delfy Staviva – Litvínov",
    type: "delfy",
    address: "S.K. Neumanna 1521",
    city: "Litvínov",
    lat: 50.6,
    lng: 13.611,
    phone: "+420 731 356 536",
    email: "litvinov@delfystaviva.cz",
    url: "https://delfystaviva.cz",
  },
  {
    id: "delfy-jiretin",
    name: "Delfy Staviva – Horní Jiřetín",
    type: "delfy",
    address: "Dolní Jiřetín – Záluží",
    city: "Horní Jiřetín",
    lat: 50.534,
    lng: 13.523,
    phone: "+420 734 594 549",
    email: "jiretin@delfystaviva.cz",
    url: "https://delfystaviva.cz",
  },
  {
    id: "delfy-podborany",
    name: "Delfy Staviva – Podbořany",
    type: "delfy",
    address: "Kadaňská 646",
    city: "Podbořany",
    lat: 50.227,
    lng: 13.409,
    phone: "+420 732 932 322",
    email: "podborany@delfystaviva.cz",
    url: "https://delfystaviva.cz",
  },
];

export const dealerConfig: Record<DealerType, { label: string; color: string; bgColor: string }> = {
  kili:       { label: "Kili",            color: "#1a6b3a", bgColor: "#d1fae5" },
  drevotrust: { label: "Dřevotrust",      color: "#1d4ed8", bgColor: "#dbeafe" },
  delfy:      { label: "Delfy Staviva",   color: "#b45309", bgColor: "#fef3c7" },
};
